import 'package:floor/floor.dart';

//Here, we are saying to floor that this is a class that defines an entity
@entity
class Meal {
  //id will be the primary key of the table. Moreover, it will be autogenerated.
  //id is nullable since it is autogenerated.
  @PrimaryKey(autoGenerate: true)
  final int? id; 

  //The carbohydrates content of the meal
  final double carbohydrates;

  //When the meal occured
  final DateTime dateTime;


  //Default constructor
  Meal(this.id, this.carbohydrates, this.dateTime);
  
}//Meal
